config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root 'recipes#index'

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
	has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
	has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
	has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :food_type
	belongs_to  :cuisine
	belongs_to :food_preference

	DIFFICULTY=%w(Easy Medium Hard)

	def self.search(query)
		where(query) if query
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_filter :siderbar_values, except: [:login, :logout]

  def siderbar_values
  	@food_preferences = FoodPreference.all.limit(10)
  	@food_types = FoodType.all.limit(10)
  	@cuisines = Cuisine.all
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:edit,:update,:destroy,:create]
  # GET /recipes
  # GET /recipes.json
  def index
    if search_params?
      @recipes = Recipe.search(search_params).paginate(per_page:12, page: params[:page])  
    else
      @recipes = Recipe.all.paginate(per_page:8, page: params[:page]) 
    end
  end


  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
  def search_params?
    params[:food_type] || params[:food_preference] || params[:cuisine] || params[:difficulty]
  end

  def search_params
    query = {}
    query[:food_type_id] = params[:food_type] if params[:food_type]
    query[:food_preference_id] = params[:food_preference] if params[:food_preference]
    query[:cuisine_id] = params[:cuisine] if params[:cuisine]
    query[:difficulty_level] = params[:difficulty] if params[:difficulty]
    return query
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FoodWorld", root_path,class:"navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
		<% if user_signed_in? %>
			<li><%=link_to "#{current_user.email}" %></li>
			<li><%= link_to "Logout",destroy_user_session_path, method: :delete%></li>
			<%else%>
			<li><%= link_to "Login", new_user_session_path%></li>
			<li  class="active"><%= link_to "SignUp",new_user_registration_path%></li>
		<%end%>
	</ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<%= form_tag recipes_path, method: 'get' do %>
<%= submit_tag "Search", :name => nil , class:"btn btn-default"%></br>

<div class="panel panel-primary" id="panels">
	<div class="panel-heading">Food Preferences</div>
	<div class="panel-body">
	<% @food_preferences.each do |fp| %>
		<!-- <p><%= fp.name%></p> -->		
		<%= radio_button_tag :food_preference, fp.id %> 
		<%= label_tag fp.name %></br>
	<%end%>
	</div>
</div>
<div class="panel panel-primary" id="panels">
	<div class="panel-heading">Food Types</div>
		<div class="panel-body">
	<% @food_types.each do |fp| %>
		<!-- <p><%= fp.name%></p> -->
		<%= radio_button_tag :food_type, fp.id %> 
		<%= label_tag fp.name %></br>
	<%end%>
	</div>
</div>
<div class="panel panel-primary" id="panels">
	<div class="panel-heading">Cuisines</div>
		<div class="panel-body">
	<% @cuisines.each do |fp| %>
		<!-- <p><%= fp.name%></p> -->
		<%= radio_button_tag :cuisine, fp.id %> 
		<%= label_tag fp.name %></br>
	<%end%>
	</div>
</div>
<div class="panel panel-primary" id="panels">
	<div class="panel-heading">Difficulty Level</div>
		<div class="panel-body">
	<% Recipe::DIFFICULTY.each do |fp| %>
		<%= radio_button_tag :difficulty, fp %> 
		<%= label_tag fp %></br>
	<%end%>
	</div>
</div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	
		<div class="container">
			<div class="row">
				<div class="col-lg-2">
					<%= render 'layouts/sidebar' %>
				</div>
				<div class="col-lg-9">
					<%= yield %>
				</div>
				
			</div>
		</div>



</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty_level %><br>
    <%= f.select :difficulty_level, Recipe::DIFFICULTY,{}, class:"form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :food_type %><br>
    <%= f.select(:food_type_id,
    options_from_collection_for_select(FoodType.all, :id,:name),
     {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :food_preference %><br>
    <%= f.select(:food_preference_id,
    options_from_collection_for_select(FoodPreference.all, :id,:name),
     {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :cuisine %><br>
    <%= f.select(:cuisine_id,
    options_from_collection_for_select(Cuisine.all, :id,:name),
     {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients, cols: 105, rows: 10 %>
  </div>
  <div class="form-group">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure, cols: 105, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit "Update",class:"btn btn-success" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe, class:"btn btn-primary btn-small" %> 
<%= link_to 'Back', recipes_path,class:"btn btn-default" %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
     <!--  <th>Ingredients</th>
      <th>Procedure</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= FoodType.find(recipe.food_type_id).name %></td>
        <td><%= FoodPreference.find(recipe.food_preference_id).name %></td>
        <td><%= Cuisine.find(recipe.cuisine_id).name %></td>

       <!--  <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td> -->
        <td><%= link_to 'Show', recipe, class:"btn btn-primary btn-small" %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_recipe_path(recipe),class:"btn btn-success btn-small" %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-small" %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @recipes %>
<br>

<%= link_to 'New Recipe', new_recipe_path,class:"btn btn-default" %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path,class:"btn btn-default"  %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Title:</strong>
  <%= @recipe.title %>
</h2>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= FoodType.find(@recipe.food_type_id).name %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= FoodPreference.find(@recipe.food_preference_id).name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= Cuisine.find(@recipe.cuisine_id).name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_recipe_path(@recipe),class:"btn btn-success" %> 
<% end -%>
<%= link_to 'Back', recipes_path,class:"btn btn-default" %>